## Global Historical Climatology Network Dataset
Variables are stored in both rows and columns
This dataset represents the daily weather records for a weather station (MX17004) in Mexico for five months in 2010.

In [29]:
from urllib.request import urlopen
import json
import pandas as pd
weather = pd.read_csv('../weather-raw.csv')
weather

,id,year,month,element,d1,d2,d3,d4,d5,d6,...,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31
0,MX17004,2010,1,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.8,NaN
1,MX17004,2010,1,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5,NaN
2,MX17004,2010,2,tmax,NaN,27.3,24.1,NaN,NaN,NaN,...,NaN,29.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MX17004,2010,2,tmin,NaN,14.4,14.4,NaN,NaN,NaN,...,NaN,10.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MX17004,2010,3,tmax,NaN,NaN,NaN,NaN,32.1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,MX17004,2010,3,tmin,NaN,NaN,NaN,NaN,14.2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MX17004,2010,4,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,36.3,NaN,NaN,NaN,NaN
7,MX17004,2010,4,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,16.7,NaN,NaN,NaN,NaN
8,MX17004,2010,5,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,33.2,NaN,NaN,NaN,NaN
9,MX17004,2010,5,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,18.2,NaN,NaN,NaN,NaN
10,MX17004,2010,6,tmax,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.1,NaN,NaN
11,MX17004,2010,6,tmin,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN
12,MX17004,2010,7,tmax,NaN,NaN,28.6,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,MX17004,2010,7,tmin,NaN,NaN,17.5,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,MX17004,2010,8,tmax,NaN,NaN,NaN,NaN,29.6,NaN,...,NaN,26.4,NaN,29.7,NaN,NaN,NaN,28.0,NaN,25.4
15,MX17004,2010,8,tmin,NaN,NaN,NaN,NaN,15.8,NaN,...,NaN,15.0,NaN,15.6,NaN,NaN,NaN,15.3,NaN,15.4
16,MX17004,2010,10,tmax,NaN,NaN,NaN,NaN,27.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,31.2,NaN,NaN,NaN
17,MX17004,2010,10,tmin,NaN,NaN,NaN,NaN,14.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
18,MX17004,2010,11,tmax,NaN,31.3,NaN,27.2,26.3,NaN,...,NaN,NaN,NaN,NaN,28.1,27.7,NaN,NaN,NaN,NaN
19,MX17004,2010,11,tmin,NaN,16.3,NaN,12.0,7.9,NaN,...,NaN,NaN,NaN,NaN,12.1,14.2,NaN,NaN,NaN,NaN
20,MX17004,2010,12,tmax,29.9,NaN,NaN,NaN,NaN,27.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,MX17004,2010,12,tmin,13.8,NaN,NaN,NaN,NaN,10.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

          id  year  month element  day  temp
0    MX17004  2010      1    tmax   d1   NaN
1    MX17004  2010      1    tmin   d1   NaN
2    MX17004  2010      2    tmax   d1   NaN
3    MX17004  2010      2    tmin   d1   NaN
4    MX17004  2010      3    tmax   d1   NaN
5    MX17004  2010      3    tmin   d1   NaN
6    MX17004  2010      4    tmax   d1   NaN
7    MX17004  2010      4    tmin   d1   NaN
8    MX17004  2010      5    tmax   d1   NaN
9    MX17004  2010      5    tmin   d1   NaN
10   MX17004  2010      6    tmax   d1   NaN
11   MX17004  2010      6    tmin   d1   NaN
12   MX17004  2010      7    tmax   d1   NaN
13   MX17004  2010      7    tmin   d1   NaN
14   MX17004  2010      8    tmax   d1   NaN
15   MX17004  2010      8    tmin   d1   NaN
16   MX17004  2010     10    tmax   d1   NaN
17   MX17004  2010     10    tmin   d1   NaN
18   MX17004  2010     11    tmax   d1   NaN
19   MX17004  2010     11    tmin   d1   NaN
20   MX17004  2010     12    tmax   d1  29.9
21   MX17004  2010     12    tmin   d1  13.8
22   MX17004  2010      1    tmax   d2   NaN
23   MX17004  2010      1    tmin   d2   NaN
24   MX17004  2010      2    tmax   d2  27.3
25   MX17004  2010      2    tmin   d2  14.4
26   MX17004  2010      3    tmax   d2   NaN
27   MX17004  2010      3    tmin   d2   NaN
28   MX17004  2010      4    tmax   d2   NaN
29   MX17004  2010      4    tmin   d2   NaN
..       ...   ...    ...     ...  ...   ...
652  MX17004  2010      8    tmax  d30   NaN
653  MX17004  2010      8    tmin  d30   NaN
654  MX17004  2010     10    tmax  d30   NaN
655  MX17004  2010     10    tmin  d30   NaN
656  MX17004  2010     11    tmax  d30   NaN
657  MX17004  2010     11    tmin  d30   NaN
658  MX17004  2010     12    tmax  d30   NaN
659  MX17004  2010     12    tmin  d30   NaN
660  MX17004  2010      1    tmax  d31   NaN
661  MX17004  2010      1    tmin  d31   NaN
662  MX17004  2010      2    tmax  d31   NaN
663  MX17004  2010      2    tmin  d31   NaN
664  MX17004  2010      3    tmax  d31   NaN
665  MX17004  2010      3    tmin  d31   NaN
666  MX17004  2010      4    tmax  d31   NaN
667  MX17004  2010      4    tmin  d31   NaN
668  MX17004  2010      5    tmax  d31   NaN
669  MX17004  2010      5    tmin  d31   NaN
670  MX17004  2010      6    tmax  d31   NaN
671  MX17004  2010      6    tmin  d31   NaN
672  MX17004  2010      7    tmax  d31   NaN
673  MX17004  2010      7    tmin  d31   NaN
674  MX17004  2010      8    tmax  d31  25.4
675  MX17004  2010      8    tmin  d31  15.4
676  MX17004  2010     10    tmax  d31   NaN
677  MX17004  2010     10    tmin  d31   NaN
678  MX17004  2010     11    tmax  d31   NaN
679  MX17004  2010     11    tmin  d31   NaN
680  MX17004  2010     12    tmax  d31   NaN
681  MX17004  2010     12    tmin  d31   NaN

[682 rows x 6 columns]

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1  d30  27.8  14.5
1        MX17004  2010      2  d11  29.7  13.4
2        MX17004  2010      2   d2  27.3  14.4
3        MX17004  2010      2  d23  29.9  10.7
4        MX17004  2010      2   d3  24.1  14.4
5        MX17004  2010      3  d10  34.5  16.8
6        MX17004  2010      3  d16  31.1  17.6
7        MX17004  2010      3   d5  32.1  14.2
8        MX17004  2010      4  d27  36.3  16.7
9        MX17004  2010      5  d27  33.2  18.2
10       MX17004  2010      6  d17  28.0  17.5
11       MX17004  2010      6  d29  30.1  18.0
12       MX17004  2010      7   d3  28.6  17.5
13       MX17004  2010      7  d14  29.9  16.5
14       MX17004  2010      8  d23  26.4  15.0
15       MX17004  2010      8   d5  29.6  15.8
16       MX17004  2010      8  d29  28.0  15.3
17       MX17004  2010      8  d13  29.8  16.5
18       MX17004  2010      8  d25  29.7  15.6
19       MX17004  2010      8  d31  25.4  15.4
20       MX17004  2010      8   d8  29.0  17.3
21       MX17004  2010     10   d5  27.0  14.0
22       MX17004  2010     10  d14  29.5  13.0
23       MX17004  2010     10  d15  28.7  10.5
24       MX17004  2010     10  d28  31.2  15.0
25       MX17004  2010     10   d7  28.1  12.9
26       MX17004  2010     11   d2  31.3  16.3
27       MX17004  2010     11   d5  26.3   7.9
28       MX17004  2010     11  d27  27.7  14.2
29       MX17004  2010     11  d26  28.1  12.1
30       MX17004  2010     11   d4  27.2  12.0
31       MX17004  2010     12   d1  29.9  13.8
32       MX17004  2010     12   d6  27.8  10.5

element       id  year  month  day  tmax  tmin
0        MX17004  2010      1  d30  27.8  14.5
1        MX17004  2010      2  d11  29.7  13.4
2        MX17004  2010      2   d2  27.3  14.4
3        MX17004  2010      2  d23  29.9  10.7
4        MX17004  2010      2   d3  24.1  14.4
5        MX17004  2010      3  d10  34.5  16.8
6        MX17004  2010      3  d16  31.1  17.6
7        MX17004  2010      3   d5  32.1  14.2
8        MX17004  2010      4  d27  36.3  16.7
9        MX17004  2010      5  d27  33.2  18.2
10       MX17004  2010      6  d17  28.0  17.5
11       MX17004  2010      6  d29  30.1  18.0
12       MX17004  2010      7   d3  28.6  17.5
13       MX17004  2010      7  d14  29.9  16.5
14       MX17004  2010      8  d23  26.4  15.0
15       MX17004  2010      8   d5  29.6  15.8
16       MX17004  2010      8  d29  28.0  15.3
17       MX17004  2010      8  d13  29.8  16.5
18       MX17004  2010      8  d25  29.7  15.6
19       MX17004  2010      8  d31  25.4  15.4
20       MX17004  2010      8   d8  29.0  17.3
21       MX17004  2010     10   d5  27.0  14.0
22       MX17004  2010     10  d14  29.5  13.0
23       MX17004  2010     10  d15  28.7  10.5
24       MX17004  2010     10  d28  31.2  15.0
25       MX17004  2010     10   d7  28.1  12.9
26       MX17004  2010     11   d2  31.3  16.3
27       MX17004  2010     11   d5  26.3   7.9
28       MX17004  2010     11  d27  27.7  14.2
29       MX17004  2010     11  d26  28.1  12.1
30       MX17004  2010     11   d4  27.2  12.0
31       MX17004  2010     12   d1  29.9  13.8
32       MX17004  2010     12   d6  27.8  10.5

KeyError: "['day'] not in index"